################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
modules/CLI \
modules/CST816 \
modules/DebugPins \
modules/RTC \
modules/ST7789 \
modules/nvm \
modules/power \
thirdparty/lvgl/fonts \
thirdparty/lvgl/gui \
thirdparty/lvgl \
thirdparty/lvgl/src/core \
thirdparty/lvgl/src/display \
thirdparty/lvgl/src/draw \
thirdparty/lvgl/src/draw/nxp/pxp \
thirdparty/lvgl/src/draw/nxp/vglite \
thirdparty/lvgl/src/draw/renesas/dave2d \
thirdparty/lvgl/src/draw/sdl \
thirdparty/lvgl/src/draw/sw/blend/helium \
thirdparty/lvgl/src/draw/sw/blend \
thirdparty/lvgl/src/draw/sw/blend/neon \
thirdparty/lvgl/src/draw/sw \
thirdparty/lvgl/src/draw/vg_lite \
thirdparty/lvgl/src/drivers/display/drm \
thirdparty/lvgl/src/drivers/display/fb \
thirdparty/lvgl/src/drivers/display/ili9341 \
thirdparty/lvgl/src/drivers/display/lcd \
thirdparty/lvgl/src/drivers/display/st7735 \
thirdparty/lvgl/src/drivers/display/st7789 \
thirdparty/lvgl/src/drivers/display/st7796 \
thirdparty/lvgl/src/drivers/evdev \
thirdparty/lvgl/src/drivers/libinput \
thirdparty/lvgl/src/drivers/nuttx \
thirdparty/lvgl/src/drivers/sdl \
thirdparty/lvgl/src/drivers/windows \
thirdparty/lvgl/src/drivers/x11 \
thirdparty/lvgl/src/font \
thirdparty/lvgl/src/indev \
thirdparty/lvgl/src/layouts/flex \
thirdparty/lvgl/src/layouts/grid \
thirdparty/lvgl/src/layouts \
thirdparty/lvgl/src/libs/barcode \
thirdparty/lvgl/src/libs/bin_decoder \
thirdparty/lvgl/src/libs/bmp \
thirdparty/lvgl/src/libs/ffmpeg \
thirdparty/lvgl/src/libs/freetype \
thirdparty/lvgl/src/libs/fsdrv \
thirdparty/lvgl/src/libs/gif \
thirdparty/lvgl/src/libs/libjpeg_turbo \
thirdparty/lvgl/src/libs/libpng \
thirdparty/lvgl/src/libs/lodepng \
thirdparty/lvgl/src/libs/lz4 \
thirdparty/lvgl/src/libs/qrcode \
thirdparty/lvgl/src/libs/rle \
thirdparty/lvgl/src/libs/rlottie \
thirdparty/lvgl/src/libs/tiny_ttf \
thirdparty/lvgl/src/libs/tjpgd \
thirdparty/lvgl/src \
thirdparty/lvgl/src/misc/cache \
thirdparty/lvgl/src/misc \
thirdparty/lvgl/src/osal \
thirdparty/lvgl/src/others/file_explorer \
thirdparty/lvgl/src/others/fragment \
thirdparty/lvgl/src/others/gridnav \
thirdparty/lvgl/src/others/ime \
thirdparty/lvgl/src/others/imgfont \
thirdparty/lvgl/src/others/monkey \
thirdparty/lvgl/src/others/observer \
thirdparty/lvgl/src/others/snapshot \
thirdparty/lvgl/src/others/sysmon \
thirdparty/lvgl/src/others/vg_lite_tvg \
thirdparty/lvgl/src/stdlib/builtin \
thirdparty/lvgl/src/stdlib/clib \
thirdparty/lvgl/src/stdlib \
thirdparty/lvgl/src/stdlib/micropython \
thirdparty/lvgl/src/stdlib/rtthread \
thirdparty/lvgl/src/themes/default \
thirdparty/lvgl/src/themes \
thirdparty/lvgl/src/themes/mono \
thirdparty/lvgl/src/themes/simple \
thirdparty/lvgl/src/tick \
thirdparty/lvgl/src/widgets/animimage \
thirdparty/lvgl/src/widgets/arc \
thirdparty/lvgl/src/widgets/bar \
thirdparty/lvgl/src/widgets/button \
thirdparty/lvgl/src/widgets/buttonmatrix \
thirdparty/lvgl/src/widgets/calendar \
thirdparty/lvgl/src/widgets/canvas \
thirdparty/lvgl/src/widgets/chart \
thirdparty/lvgl/src/widgets/checkbox \
thirdparty/lvgl/src/widgets/dropdown \
thirdparty/lvgl/src/widgets/image \
thirdparty/lvgl/src/widgets/imagebutton \
thirdparty/lvgl/src/widgets/keyboard \
thirdparty/lvgl/src/widgets/label \
thirdparty/lvgl/src/widgets/led \
thirdparty/lvgl/src/widgets/line \
thirdparty/lvgl/src/widgets/list \
thirdparty/lvgl/src/widgets/menu \
thirdparty/lvgl/src/widgets/msgbox \
thirdparty/lvgl/src/widgets/objx_templ \
thirdparty/lvgl/src/widgets/roller \
thirdparty/lvgl/src/widgets/scale \
thirdparty/lvgl/src/widgets/slider \
thirdparty/lvgl/src/widgets/span \
thirdparty/lvgl/src/widgets/spinbox \
thirdparty/lvgl/src/widgets/spinner \
thirdparty/lvgl/src/widgets/switch \
thirdparty/lvgl/src/widgets/table \
thirdparty/lvgl/src/widgets/tabview \
thirdparty/lvgl/src/widgets/textarea \
thirdparty/lvgl/src/widgets/tileview \
thirdparty/lvgl/src/widgets/win \

